"""
LoopHive — Platform Policies

Hardcoded policies for publishing and ads platforms as of mid-2026.
"""

from __future__ import annotations


class PlatformPolicyDatabase:
    """Policy rules database for content platforms."""

    POLICIES = {
        "medium": {
            "ai_allowed": True,
            "paywall_allowed_for_ai": False,  # Medium bans AI from Partner Program paywalls
            "disclosure_required": True,
            "allowed_types": ["articles", "guides"],
            "banned_types": ["low-effort-spam", "direct-affiliate-links-only"],
        },
        "substack": {
            "ai_allowed": True,
            "paywall_allowed_for_ai": True,  # Substack allows paid newsletters regardless of AI
            "disclosure_required": False,  # Optional but recommended
            "allowed_types": ["newsletters", "podcasts", "articles"],
            "banned_types": [],
        },
        "amazon": {
            "ai_allowed": True,
            "disclosure_required": True,  # FTC requires affiliate disclosure
            "allowed_types": ["product_reviews", "lists"],
            "banned_types": ["scraped_content", "autogenerated_pages_without_value"],
        },
        "adsense": {
            "ai_allowed": True,
            "disclosure_required": False,  # E-E-A-T matters, not AI tag itself
            "allowed_types": ["niche_site_articles"],
            "banned_types": ["scaled_content_abuse", "scraped_text"],
        },
        "x": {
            "ai_allowed": True,
            "disclosure_required": True,  # Sensitive or realistic AI media must be labeled
            "allowed_types": ["threads", "posts"],
            "banned_types": ["ai_slop_video_spam"],
        }
    }

    @classmethod
    def get_policy(cls, platform: str) -> dict | None:
        """Get the policy dictionary for a platform."""
        return cls.POLICIES.get(platform.lower())

    @classmethod
    def is_content_allowed(cls, platform: str, content_type: str) -> bool:
        """Check if a specific content type is allowed on a platform."""
        policy = cls.get_policy(platform)
        if not policy:
            return True
            
        # Check banned types
        if content_type in policy.get("banned_types", []):
            return False
            
        # Check allowed types
        allowed = policy.get("allowed_types", [])
        if allowed and content_type not in allowed:
            return False
            
        return True
